import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import toast, { Toaster } from 'react-hot-toast';



export const metadata: Metadata = {
  title: "Travel Itinerary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Toaster />
        <div className=" !bg-[#F0F2F5] w-full flex flex-col justify-center items-center min-h-screen overflow-auto">
          <Header />
          <div className="w-[95%] flex pt-[100px]  ">
            <SideBar />
            <main className="w-full md:pl-[310px]  flex justify-center  ">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
