import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <div className=" !bg-[#F0F2F5] w-full flex flex-col justify-center items-center min-h-screen overflow-auto">
          <Header />
          <div className="w-[95%] flex pt-[100px]  ">
            <SideBar />
            <main className="w-full md:pl-[350px]  flex justify-center  ">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
